### ISSUE TITLE
Составить интро

### ISSUE THREAD

**Issue by madmaxWMFU** [madmaxWMFU/homepage#4]
Составить интро (вступление), где в 2-4 предложениях описать, что заказчик делает, что нравится делать, что хочется делать лучше, что важно делать, и т.д.

**Comment by MagneticBabay** [comment]
- Hello! I am a beginner front-end developer with little experience in application development and database modeling. I strive to create apps in line with new technology trends. I hope if I go to the future recruitment at the Binary Studio Academy I will learn all the necessary knowledge.

**Comment by madmaxWMFU** [comment]
Thank's
