### ISSUE TITLE
Составить блок контактной информации

### ISSUE THREAD

**Issue by madmaxWMFU** [madmaxWMFU/homepage#5]
Ссылки на соцсети (Facebook или Instagram, и т.п.), номер телефона или адрес электронной почты, т.п. Может не все ссылки в мире, а только те, которые действительно уместны.

**Comment by MagneticBabay** [comment]
**Maksym Yasenovyi**
- https://www.linkedin.com/in/maksym-yasenovyi-9a7aaa20b/
- https://github.com/madmaxWMFU
- https://www.fb.com/maksymyasenovyi
