### ISSUE TITLE
Составить дополнительные информационные блоки

### ISSUE THREAD

**Issue by madmaxWMFU** [madmaxWMFU/homepage#7]
Можно сделать резюме менее формальным, добавив дополнительные блоки, которые содержат полезную информацию, но подают её в "развлекательной" форме. Например, что нравится и не нравится, сильные и слабые стороны, перечень навыков или хобби, инфографика или же интерактивные модули, и т.п. Стоит написать контент такого блока раньше, чем начинать верстку, потому что его размеры будут влиять на размещение элементов на странице.

**Comment by MagneticBabay** [comment]
Skills
HTML CSS JS A11Y JQUERY NODEJS NPM BOOTSTRAP PRETTIER ESLINT MICROSOFT OFFICE PHP DELPHI PYTHON BASH LINUX WINDOWS MACOS MYSQL MICROSOFT SQL

Character
STABLE, HARDLY, FREE IN COMMUNICATION, GOOD MEMORY, RELIABLE AND PATIENT, CREATIVE, HARDWORKING, DREAMY.

Likes😃
HUMOUR COMEDY MOVIES GYM AIRSOFT GUNS F1

Dislikes😞
STUBBORNNESS, DEPENDENCE ON COMFORT

Wants🥺
TO BE FIT AND HEALTHY
